Les fichiers <a href="https://capytale2.ac-paris.fr/web/sites/default/files/2024/02-28/13-23-45/listeAuteur2.csv">listeAuteur2.csv</a> , <a href="https://capytale2.ac-paris.fr/web/sites/default/files/2024/02-28/13-23-45/listeLivre.csv">listeLivre.csv</a> et <a href="https://capytale2.ac-paris.fr/web/sites/default/files/2024/02-28/13-23-45/listeLivre.csv">listeNationalite.csv</a> sont attachés à ce NoteBook.

### On rappelle les instructions pour écrire et lire en CSV, une table sous forme de liste de dictionnaire

In [ ]:
import csv 

with  open("matable.csv","w")as sortie:
    objet=csv.DictWriter(sortie,['Nom','Grec','Maths','Philosophie'],delimiter=",") 
    objet.writeheader() 
    objet.writerows(table)

fichier=open("matable.csv",encoding='utf8') 
table=list(csv.DictReader(fichier,delimiter=",")) 
fichier.close()
print(table)

On donne la fonction `affiche` qui permet d'afficher une table sous forme de liste de dictionnaire

In [1]:
def affiche(tableau:list,a=0,b=0,numLigne=False) -> None:
    """Affichage d'un tableau"""
    
    if tableau==[]:
        print("Tableau Vide")
        return
    tab="\t\t"
    if a==0 and b==0:
        a=0
        b=len(tableau)
    elif b==0:
        b=a
        a=0
    else:
        a=a-1
    if numLigne:
            print("ligne"+"\t",end="")
    for cle in tableau[0]:
        if len(str(cle))>=8:
            print(str(cle)+"\t",end="")
        else:
            print(str(cle)+tab,end="")
    for i in range(a,b):
        print()
        if numLigne:
                print(str(i+1)+"\t",end="")
        for valeur in tableau[i].values():

            if len(str(valeur))>=8:
                print(str(valeur)+"\t",end="")
            else:
                print(str(valeur)+tab,end="")
    print()


!!! note Utilisation de `affiche`
+ `affiche(table)` affiche toutes les lignes.
+ `affiche(table,i,j)` affiche les lignes i inclus  à j inclus.
+ `affiche(table,i,j,True)` affiche les lignes i à j et les numéros de ligne.
!!!

# Exercice 1 
  
On vous donne la table  suivante:
|numeroAuteur|nom |prenom|annee_naissance|
|-|-|-|-|
|1|Orwell|George |1903 |
|2|Herbert| Franck|1920| 
|3|Asimov| Isaac |1920 |

1. Ecrivez le code python pour créer un tableau `TableauAuteur1` sous forme de liste de dictionnaires contenant les informations ci_dessus.
2. Enregistrer le tableau dans un fichier `listeAuteur1.csv`. On utilisera la virgule comme délimiteur.

# Exercice 2

Ouvrir Les fichiers  <a href="https://capytale2.ac-paris.fr/web/sites/default/files/2024/02-28/13-23-45/listeAuteur2.csv">listeAuteur2.csv</a> , <a href="https://capytale2.ac-paris.fr/web/sites/default/files/2024/02-28/13-23-45/listeLivre.csv">listeLivre.csv</a> et <a href="https://capytale2.ac-paris.fr/web/sites/default/files/2024/02-28/13-23-45/listeLivre.csv">listeNationalite.csv</a>. Mettre les tableaux resultats sous forme de liste de dictionnaires. La virgule est le délémiteur.

On appellera les tableaux respectif `TableauAuteur2`, `TableauLivre` et `TableauNationalite`

# exercice 3

Faire la réunion des tableaux `TableauAuteur1` et `TableauAuteur2` dans un tableau nommé `TableauAuteur`

## Dans le cas où vous n'arrivez pas à répondre à la question précédente vous pouvez exécuter la cellule suivante pour continuer. Cela charge les tableaux sous le bon format.

In [2]:
from _creationDeTableauGroupeB import TableauAuteur, TableauLivre

# Exercice 4
Afficher les 5 premiéres lignes des tableaux `TableauAuteur` , `TableauLivre` et `TableauNationalite`

+ Affichage de `TableauAuteur`

+ Affichage de `TableauLivre`

+ Affichage de `TableauNationalite`

# Exercice 5
Faites une fonction `NombreChamps(tableau)` qui prend une liste de dictionnaires en paramétre et renvoie le nombre de champs

Exemple:
```python
>>>NombreChamps(TableauAuteur)
4
>>>NombreChamps([{'Nom': 'pie', 'couleur1': 'noire'},
                {'Nom': 'aigle', 'couleur1': 'brun'},
                {'Nom': 'chouette', 'couleur1': 'brun'}])
2
```

# Exercice 6
Trier le tableau `TableauLivre` par ordre alphabétique de titre. Afficher le tableau trié.

# Exercice 7
Créer un tableau `TABLEAUTEUR` qui contient les personnes de `TableauAuteur` mais où l'on remplace les champs `nom` et `prenom` par un seul champ `NomComplet` qui contient la concaténation du nom et du prénom des personnes du  tableau `TableauAuteur`. N'oubliez pas l'espace.

# Exercice 8

Faire la fusion des tableaux `TableauAuteur` et `TableauNationalite` dans un tableau `TableauAuteurComplet`de telle maniére que chaque ligne du tableau contienne un numéro d'auteur associé à son nom, prénom, année de naissance et sa nationalité. Afficher les 5 premières lignes du tableau.

# Exercice 9
Ecrire une fonction `chercherAuteur(livre,TableauLivre,TableauAuteur)` qui prend en paramétre le titre d'un livre, un tableau de livre et un tableau d'auteurs. Cette fonction renvoie le nom de famille de l'auteur du livre proposé en paramétre.

```python
>>>chercherAuteur("Le K",TableauLivre,TableauAuteur)
'Buzzati'
```